name: Maven Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Create settings.xml with Nexus credentials from secrets
      - name: Setup Maven settings.xml
        run: |
          mkdir -p $HOME/.m2
          cat <<EOF > $HOME/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USER }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 4. Build deploy
      - name: Build and deploy
        run: mvn clean deploy --settings $HOME/.m2/settings.xml
