name: ci/cd pipeline to deploy to tomcat

on: 
  push:
    branches: master  #runs pipeline only when pushing to master branch
jobs:
   build-deploy:
     runs-on: ubuntu-latest
     
     steps:
           # checkout repo
           - name: checkout code
             uses: actions/checkout@v3
         
           # set-up java
           - name: set-up jdk
             uses: actions/setup-java@v3
             with:
               distribution: 'temurin'
               java-version: '11'
           
           # build with maven(update)
           - name: package with maven
             run: mvn clean package

          # Deploy to Tomcat
           - name: deploy war to tomcat
             run: | 
                curl -v -u user:password \
                -X POST \
                -H "Content-Type: application/octet-stream" \
                --data-binary @target/TrainBook-1.0.0-SNAPSHOT.war \
                "http://<host>:8080/manager/text/deploy?path=/TrainBook&update=true"
